name: Build and Push to ACR

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for Azure Login
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to ACR
      run: |
        az acr login --name Rstudentacr

    - name: Build and Push Docker Image
      run: |
        docker build -t Rstudentacr.azurecr.io/myapp:latest .
        docker push Rstudentacr.azurecr.io/myapp:latest

    - name: Verify Pushed Image
      run: |
        az acr repository show-tags --name Rstudentacr --repository myapp
